---
# Certbot handlers

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  become: yes

- name: reload postfix
  systemd:
    name: postfix
    state: reloaded
  become: yes

- name: reload dovecot
  systemd:
    name: dovecot
    state: reloaded
  become: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: yes

- name: restart postfix
  systemd:
    name: postfix
    state: restarted
  become: yes

- name: restart dovecot
  systemd:
    name: dovecot
    state: restarted
  become: yes
