---
galaxy_info:
  author: Mail Admin
  description: Configure email autoconfig/autodiscover for Thunderbird and Outlook
  company: grufo.at
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - mail
    - email
    - autoconfig
    - autodiscover
    - thunderbird
    - outlook
    - nginx
    - certbot

dependencies: []
