---
# roles/fail2ban/tasks/configure.yml

- name: Configure fail2ban jail.local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart fail2ban

- name: Configure UFW action for fail2ban
  template:
    src: action-ufw.conf.j2
    dest: /etc/fail2ban/action.d/ufw.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban

- name: Create fail2ban whitelist
  template:
    src: whitelist.conf.j2
    dest: /etc/fail2ban/jail.d/whitelist.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban

- name: Configure email notifications
  template:
    src: sendmail-common.local.j2
    dest: /etc/fail2ban/action.d/sendmail-common.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  when: fail2ban_enable_email | default(true)
